name: Release

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        echo -e "[url \"https://github.com/\"]\n\tinsteadOf = ssh://git@github.com/" > ~/.gitconfig
        yarn install && yarn build
    - run: zip -r stremio-web.zip ./build
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: stremio-web.zip
        asset_name: stremio-web.zip
        tag: ${{ github.ref }}
        overwrite: true
    - run: |
        curl -H "Content-Type: application/zip" \
             -H "Authorization: Bearer ${{ secrets.netlify_access_token }}" \
             --data-binary "@stremio-web.zip" \
             https://api.netlify.com/api/v1/sites/stremio-staging.netlify.com/deploys
    
